/** Badge catalog — icons from mezotv/discord-badges (MIT). See public/badges/NOTICE.txt */
export type BadgeGroup =
  | 'general'
  | 'bots'
  | 'gifting'
  | 'accountAge'
  | 'streaming'
  | 'gameTime'
  | 'gameVariety'
  | 'nitro'
  | 'nitroLegacy'
  | 'boost'
  | 'server'
  | 'special'
  | 'tags'
  | 'fame'
  | 'legacy'
  | 'other'

export type BadgeDef = {
  key: string
  /** public_flags bit; 0 = catalog-only */
  bit: number
  nameEn: string
  nameRu: string
  descriptionEn?: string
  descriptionRu?: string
  icon: string
  group: BadgeGroup
}

const badgeUrl = (file: string) => `${import.meta.env.BASE_URL}badges/${file}`

export const BADGE_CATALOG: BadgeDef[] = [
  {
    key: 'discord_staff_svg',
    bit: 1 << 0,
    nameEn: 'Discord Staff',
    nameRu: 'Сотрудник Discord',
    descriptionEn: 'Official Discord employee.',
    descriptionRu: 'Официальный сотрудник Discord.',
    icon: badgeUrl('discord-staff.svg'),
    group: 'general',
  },
  {
    key: 'discord_partner_svg',
    bit: 1 << 1,
    nameEn: 'Partnered Server Owner',
    nameRu: 'Владелец партнёрского сервера',
    descriptionEn: 'Owns a Discord Partner server.',
    descriptionRu: 'Владелец сервера Discord Partner.',
    icon: badgeUrl('discord-partner.svg'),
    group: 'general',
  },
  {
    key: 'hype_squad_events_svg',
    bit: 1 << 2,
    nameEn: 'HypeSquad Events',
    nameRu: 'HypeSquad Events',
    descriptionEn: 'HypeSquad Events member.',
    descriptionRu: 'Участник HypeSquad Events.',
    icon: badgeUrl('hype-squad-events.svg'),
    group: 'general',
  },
  {
    key: 'discord_bug_hunter_green_svg',
    bit: 1 << 3,
    nameEn: 'Bug Hunter Level 1',
    nameRu: 'Bug Hunter Level 1',
    descriptionEn: 'Discord Testers bug hunter.',
    descriptionRu: 'Охотник за багами Discord Testers.',
    icon: badgeUrl('discord-bug-hunter-green.svg'),
    group: 'general',
  },
  {
    key: 'hype_squad_bravery_svg',
    bit: 1 << 6,
    nameEn: 'HypeSquad Bravery',
    nameRu: 'HypeSquad Bravery',
    descriptionEn: 'House Bravery.',
    descriptionRu: 'Дом Bravery.',
    icon: badgeUrl('hype-squad-bravery.svg'),
    group: 'general',
  },
  {
    key: 'hype_squad_brilliance_svg',
    bit: 1 << 7,
    nameEn: 'HypeSquad Brilliance',
    nameRu: 'HypeSquad Brilliance',
    descriptionEn: 'House Brilliance.',
    descriptionRu: 'Дом Brilliance.',
    icon: badgeUrl('hype-squad-brilliance.svg'),
    group: 'general',
  },
  {
    key: 'hype_squad_balance_svg',
    bit: 1 << 8,
    nameEn: 'HypeSquad Balance',
    nameRu: 'HypeSquad Balance',
    descriptionEn: 'House Balance.',
    descriptionRu: 'Дом Balance.',
    icon: badgeUrl('hype-squad-balance.svg'),
    group: 'general',
  },
  {
    key: 'discord_early_supporter_svg',
    bit: 1 << 9,
    nameEn: 'Early Supporter',
    nameRu: 'Early Supporter',
    descriptionEn: 'Early Nitro purchaser.',
    descriptionRu: 'Ранний покупатель Nitro.',
    icon: badgeUrl('discord-early-supporter.svg'),
    group: 'general',
  },
  {
    key: 'discord_bug_hunter_gold_svg',
    bit: 1 << 14,
    nameEn: 'Bug Hunter Level 2',
    nameRu: 'Bug Hunter Level 2',
    descriptionEn: 'Highest Discord Testers tier.',
    descriptionRu: 'Высший уровень Discord Testers.',
    icon: badgeUrl('discord-bug-hunter-gold.svg'),
    group: 'general',
  },
  {
    key: 'discord_bot_dev_svg',
    bit: 1 << 17,
    nameEn: 'Early Verified Bot Developer',
    nameRu: 'Early Verified Bot Developer',
    descriptionEn: 'Verified bot owner before Aug 2020.',
    descriptionRu: 'Владелец верифицированного бота до авг. 2020.',
    icon: badgeUrl('discord-bot-dev.svg'),
    group: 'general',
  },
  {
    key: 'discord_mod_svg',
    bit: 1 << 18,
    nameEn: 'Moderator Programs Alumni',
    nameRu: 'Moderator Programs Alumni',
    descriptionEn: 'Moderator programs alumni.',
    descriptionRu: 'Выпускник программ модерации.',
    icon: badgeUrl('discord-mod.svg'),
    group: 'general',
  },
  {
    key: 'active_developer_svg',
    bit: 1 << 22,
    nameEn: 'Active Developer',
    nameRu: 'Active Developer',
    descriptionEn: 'Owns an active Discord application.',
    descriptionRu: 'Владелец активного приложения Discord.',
    icon: badgeUrl('active-developer.svg'),
    group: 'general',
  },
  {
    key: 'quest_png',
    bit: 0,
    nameEn: 'Completed a Quest',
    nameRu: 'Завершил Quest',
    descriptionEn: 'Completed a Discord Quest.',
    descriptionRu: 'Завершил Discord Quest.',
    icon: badgeUrl('quest.png'),
    group: 'general',
  },
  {
    key: 'orb_svg',
    bit: 0,
    nameEn: 'Orbs Apprentice',
    nameRu: 'Orbs Apprentice',
    descriptionEn: 'Orbs exclusives shop unlock.',
    descriptionRu: 'Разблокировка Orbs Exclusives.',
    icon: badgeUrl('orb.svg'),
    group: 'general',
  },
  {
    key: 'last_meadow_png',
    bit: 0,
    nameEn: 'Last Meadow Online',
    nameRu: 'Last Meadow Online',
    descriptionEn: 'Last Meadow event badge.',
    descriptionRu: 'Бейдж ивента Last Meadow.',
    icon: badgeUrl('last-meadow.png'),
    group: 'general',
  },
  {
    key: 'username_png',
    bit: 0,
    nameEn: 'Originally known as',
    nameRu: 'Originally known as',
    descriptionEn: 'Legacy username migration tag.',
    descriptionRu: 'Метка миграции на новые username.',
    icon: badgeUrl('username.png'),
    group: 'general',
  },
  {
    key: 'special_discord_lootbox_svg',
    bit: 0,
    nameEn: 'A clown, for a limited time',
    nameRu: 'Клоун (лимитированный)',
    descriptionEn: 'April Fools lootbox unlock.',
    descriptionRu: 'Разблокировка April Fools lootbox.',
    icon: badgeUrl('special/discord-lootbox.svg'),
    group: 'general',
  },
  {
    key: 'discord_nitro_svg',
    bit: 0,
    nameEn: 'Discord Nitro',
    nameRu: 'Discord Nitro',
    descriptionEn: 'Active Nitro subscription.',
    descriptionRu: 'Активная подписка Nitro.',
    icon: badgeUrl('discord-nitro.svg'),
    group: 'nitro',
  },
  {
    key: 'discord_nitro_basic_svg',
    bit: 0,
    nameEn: 'Discord Nitro Basic',
    nameRu: 'Discord Nitro Basic',
    descriptionEn: 'Nitro Basic / Classic style badge.',
    descriptionRu: 'Бейдж Nitro Basic / Classic.',
    icon: badgeUrl('discord-nitro-basic.svg'),
    group: 'nitro',
  },
  {
    key: 'supports_commands_svg',
    bit: 1 << 19,
    nameEn: 'Supports Commands',
    nameRu: 'Supports Commands',
    descriptionEn: 'Bot uses application commands.',
    descriptionRu: 'Бот использует application commands.',
    icon: badgeUrl('supports-commands.svg'),
    group: 'bots',
  },
  {
    key: 'automod_svg',
    bit: 1 << 24,
    nameEn: 'Uses AutoMod',
    nameRu: 'Uses AutoMod',
    descriptionEn: '100 active AutoMod rules.',
    descriptionRu: '100 активных правил AutoMod.',
    icon: badgeUrl('automod.svg'),
    group: 'bots',
  },
  {
    key: 'premium_bot_png',
    bit: 0,
    nameEn: 'App Premium',
    nameRu: 'App Premium',
    descriptionEn: 'Server has the app’s premium.',
    descriptionRu: 'На сервере есть premium приложения.',
    icon: badgeUrl('premium-bot.png'),
    group: 'bots',
  },
  {
    key: 'gifting_patron_png',
    bit: 0,
    nameEn: 'Patron',
    nameRu: 'Patron',
    descriptionEn: 'Sent 1 Shop/Wishlist gift.',
    descriptionRu: 'Отправил 1 подарок из Shop/Wishlist.',
    icon: badgeUrl('gifting/patron.png'),
    group: 'gifting',
  },
  {
    key: 'gifting_champion_png',
    bit: 0,
    nameEn: 'Champion',
    nameRu: 'Champion',
    descriptionEn: 'Sent 2 Shop/Wishlist gifts.',
    descriptionRu: 'Отправил 2 подарка из Shop/Wishlist.',
    icon: badgeUrl('gifting/champion.png'),
    group: 'gifting',
  },
  {
    key: 'gifting_luminary_png',
    bit: 0,
    nameEn: 'Luminary',
    nameRu: 'Luminary',
    descriptionEn: 'Sent 3 Shop/Wishlist gifts.',
    descriptionRu: 'Отправил 3 подарка из Shop/Wishlist.',
    icon: badgeUrl('gifting/luminary.png'),
    group: 'gifting',
  },
  {
    key: 'gifting_icon_png',
    bit: 0,
    nameEn: 'Icon',
    nameRu: 'Icon',
    descriptionEn: 'Sent 6 Shop/Wishlist gifts.',
    descriptionRu: 'Отправил 6 подарков из Shop/Wishlist.',
    icon: badgeUrl('gifting/icon.png'),
    group: 'gifting',
  },
  {
    key: 'gifting_hero_png',
    bit: 0,
    nameEn: 'Hero',
    nameRu: 'Hero',
    descriptionEn: 'Sent 10 Shop/Wishlist gifts.',
    descriptionRu: 'Отправил 10 подарков из Shop/Wishlist.',
    icon: badgeUrl('gifting/hero.png'),
    group: 'gifting',
  },
  {
    key: 'gifting_legend_png',
    bit: 0,
    nameEn: 'Legend',
    nameRu: 'Legend',
    descriptionEn: 'Sent 20 Shop/Wishlist gifts.',
    descriptionRu: 'Отправил 20 подарков из Shop/Wishlist.',
    icon: badgeUrl('gifting/legend.png'),
    group: 'gifting',
  },
  {
    key: 'account_age_seed_svg',
    bit: 0,
    nameEn: 'Seed',
    nameRu: 'Seed',
    descriptionEn: 'Account age: 1 year.',
    descriptionRu: 'Возраст аккаунта: 1 год.',
    icon: badgeUrl('account-age/seed.svg'),
    group: 'accountAge',
  },
  {
    key: 'account_age_sprout_svg',
    bit: 0,
    nameEn: 'Sprout',
    nameRu: 'Sprout',
    descriptionEn: 'Account age: 2 years.',
    descriptionRu: 'Возраст аккаунта: 2 года.',
    icon: badgeUrl('account-age/sprout.svg'),
    group: 'accountAge',
  },
  {
    key: 'account_age_bud_svg',
    bit: 0,
    nameEn: 'Bud',
    nameRu: 'Bud',
    descriptionEn: 'Account age: 3 years.',
    descriptionRu: 'Возраст аккаунта: 3 года.',
    icon: badgeUrl('account-age/bud.svg'),
    group: 'accountAge',
  },
  {
    key: 'account_age_sapling_svg',
    bit: 0,
    nameEn: 'Sapling',
    nameRu: 'Sapling',
    descriptionEn: 'Account age: 4 years.',
    descriptionRu: 'Возраст аккаунта: 4 года.',
    icon: badgeUrl('account-age/sapling.svg'),
    group: 'accountAge',
  },
  {
    key: 'account_age_blossom_svg',
    bit: 0,
    nameEn: 'Blossom',
    nameRu: 'Blossom',
    descriptionEn: 'Account age: 5 years.',
    descriptionRu: 'Возраст аккаунта: 5 лет.',
    icon: badgeUrl('account-age/blossom.svg'),
    group: 'accountAge',
  },
  {
    key: 'account_age_redwood_svg',
    bit: 0,
    nameEn: 'Redwood',
    nameRu: 'Redwood',
    descriptionEn: 'Account age: 6 years.',
    descriptionRu: 'Возраст аккаунта: 6 лет.',
    icon: badgeUrl('account-age/redwood.svg'),
    group: 'accountAge',
  },
  {
    key: 'account_age_sequoia_svg',
    bit: 0,
    nameEn: 'Sequoia',
    nameRu: 'Sequoia',
    descriptionEn: 'Account age: 7 years.',
    descriptionRu: 'Возраст аккаунта: 7 лет.',
    icon: badgeUrl('account-age/sequoia.svg'),
    group: 'accountAge',
  },
  {
    key: 'account_age_bristlecone_svg',
    bit: 0,
    nameEn: 'Bristlecone',
    nameRu: 'Bristlecone',
    descriptionEn: 'Account age: 8 years.',
    descriptionRu: 'Возраст аккаунта: 8 лет.',
    icon: badgeUrl('account-age/bristlecone.svg'),
    group: 'accountAge',
  },
  {
    key: 'account_age_stromatolite_svg',
    bit: 0,
    nameEn: 'Stromatolite',
    nameRu: 'Stromatolite',
    descriptionEn: 'Account age: 9 years.',
    descriptionRu: 'Возраст аккаунта: 9 лет.',
    icon: badgeUrl('account-age/stromatolite.svg'),
    group: 'accountAge',
  },
  {
    key: 'account_age_primordial_svg',
    bit: 0,
    nameEn: 'Primordial',
    nameRu: 'Primordial',
    descriptionEn: 'Account age: 10+ years.',
    descriptionRu: 'Возраст аккаунта: 10+ лет.',
    icon: badgeUrl('account-age/primordial.svg'),
    group: 'accountAge',
  },
  {
    key: 'streaming_newcomer_svg',
    bit: 0,
    nameEn: 'Newcomer',
    nameRu: 'Newcomer',
    descriptionEn: 'Streamed 1 hour.',
    descriptionRu: 'Стримил 1 час.',
    icon: badgeUrl('streaming/newcomer.svg'),
    group: 'streaming',
  },
  {
    key: 'streaming_fledgling_svg',
    bit: 0,
    nameEn: 'Fledgling',
    nameRu: 'Fledgling',
    descriptionEn: 'Streamed 5 hours.',
    descriptionRu: 'Стримил 5 часов.',
    icon: badgeUrl('streaming/fledgling.svg'),
    group: 'streaming',
  },
  {
    key: 'streaming_breakout_svg',
    bit: 0,
    nameEn: 'Breakout',
    nameRu: 'Breakout',
    descriptionEn: 'Streamed 20 hours.',
    descriptionRu: 'Стримил 20 часов.',
    icon: badgeUrl('streaming/breakout.svg'),
    group: 'streaming',
  },
  {
    key: 'streaming_standout_svg',
    bit: 0,
    nameEn: 'Standout',
    nameRu: 'Standout',
    descriptionEn: 'Streamed 75 hours.',
    descriptionRu: 'Стримил 75 часов.',
    icon: badgeUrl('streaming/standout.svg'),
    group: 'streaming',
  },
  {
    key: 'streaming_trendsetter_svg',
    bit: 0,
    nameEn: 'Trendsetter',
    nameRu: 'Trendsetter',
    descriptionEn: 'Streamed 150 hours.',
    descriptionRu: 'Стримил 150 часов.',
    icon: badgeUrl('streaming/trendsetter.svg'),
    group: 'streaming',
  },
  {
    key: 'streaming_headliner_svg',
    bit: 0,
    nameEn: 'Headliner',
    nameRu: 'Headliner',
    descriptionEn: 'Streamed 300 hours.',
    descriptionRu: 'Стримил 300 часов.',
    icon: badgeUrl('streaming/headliner.svg'),
    group: 'streaming',
  },
  {
    key: 'streaming_star_svg',
    bit: 0,
    nameEn: 'Star',
    nameRu: 'Star',
    descriptionEn: 'Streamed 500 hours.',
    descriptionRu: 'Стримил 500 часов.',
    icon: badgeUrl('streaming/star.svg'),
    group: 'streaming',
  },
  {
    key: 'streaming_sensation_svg',
    bit: 0,
    nameEn: 'Sensation',
    nameRu: 'Sensation',
    descriptionEn: 'Streamed 1,000 hours.',
    descriptionRu: 'Стримил 1 000 часов.',
    icon: badgeUrl('streaming/sensation.svg'),
    group: 'streaming',
  },
  {
    key: 'streaming_visionary_svg',
    bit: 0,
    nameEn: 'Visionary',
    nameRu: 'Visionary',
    descriptionEn: 'Streamed 2,000 hours.',
    descriptionRu: 'Стримил 2 000 часов.',
    icon: badgeUrl('streaming/visionary.svg'),
    group: 'streaming',
  },
  {
    key: 'streaming_phenomenon_svg',
    bit: 0,
    nameEn: 'Phenomenon',
    nameRu: 'Phenomenon',
    descriptionEn: 'Streamed 5,000+ hours.',
    descriptionRu: 'Стримил 5 000+ часов.',
    icon: badgeUrl('streaming/phenomenon.svg'),
    group: 'streaming',
  },
  {
    key: 'game_time_casual_svg',
    bit: 0,
    nameEn: 'Casual',
    nameRu: 'Casual',
    descriptionEn: 'Played 1 hour with Discord open.',
    descriptionRu: 'Играл 1 час с открытым Discord.',
    icon: badgeUrl('game-time/casual.svg'),
    group: 'gameTime',
  },
  {
    key: 'game_time_recreational_svg',
    bit: 0,
    nameEn: 'Recreational',
    nameRu: 'Recreational',
    descriptionEn: 'Played 5 hours with Discord open.',
    descriptionRu: 'Играл 5 часов с открытым Discord.',
    icon: badgeUrl('game-time/recreational.svg'),
    group: 'gameTime',
  },
  {
    key: 'game_time_dedicated_svg',
    bit: 0,
    nameEn: 'Dedicated',
    nameRu: 'Dedicated',
    descriptionEn: 'Played 20 hours with Discord open.',
    descriptionRu: 'Играл 20 часов с открытым Discord.',
    icon: badgeUrl('game-time/dedicated.svg'),
    group: 'gameTime',
  },
  {
    key: 'game_time_committed_svg',
    bit: 0,
    nameEn: 'Committed',
    nameRu: 'Committed',
    descriptionEn: 'Played 75 hours with Discord open.',
    descriptionRu: 'Играл 75 часов с открытым Discord.',
    icon: badgeUrl('game-time/committed.svg'),
    group: 'gameTime',
  },
  {
    key: 'game_time_serious_svg',
    bit: 0,
    nameEn: 'Serious',
    nameRu: 'Serious',
    descriptionEn: 'Played 150 hours with Discord open.',
    descriptionRu: 'Играл 150 часов с открытым Discord.',
    icon: badgeUrl('game-time/serious.svg'),
    group: 'gameTime',
  },
  {
    key: 'game_time_devoted_svg',
    bit: 0,
    nameEn: 'Devoted',
    nameRu: 'Devoted',
    descriptionEn: 'Played 300 hours with Discord open.',
    descriptionRu: 'Играл 300 часов с открытым Discord.',
    icon: badgeUrl('game-time/devoted.svg'),
    group: 'gameTime',
  },
  {
    key: 'game_time_seasoned_svg',
    bit: 0,
    nameEn: 'Seasoned',
    nameRu: 'Seasoned',
    descriptionEn: 'Played 500 hours with Discord open.',
    descriptionRu: 'Играл 500 часов с открытым Discord.',
    icon: badgeUrl('game-time/seasoned.svg'),
    group: 'gameTime',
  },
  {
    key: 'game_time_ironclad_svg',
    bit: 0,
    nameEn: 'Ironclad',
    nameRu: 'Ironclad',
    descriptionEn: 'Played 1,000 hours with Discord open.',
    descriptionRu: 'Играл 1 000 часов с открытым Discord.',
    icon: badgeUrl('game-time/ironclad.svg'),
    group: 'gameTime',
  },
  {
    key: 'game_time_unshakeable_svg',
    bit: 0,
    nameEn: 'Unshakeable',
    nameRu: 'Unshakeable',
    descriptionEn: 'Played 2,000 hours with Discord open.',
    descriptionRu: 'Играл 2 000 часов с открытым Discord.',
    icon: badgeUrl('game-time/unshakeable.svg'),
    group: 'gameTime',
  },
  {
    key: 'game_time_eternal_svg',
    bit: 0,
    nameEn: 'Eternal',
    nameRu: 'Eternal',
    descriptionEn: 'Played 5,000+ hours with Discord open.',
    descriptionRu: 'Играл 5 000+ часов с открытым Discord.',
    icon: badgeUrl('game-time/eternal.svg'),
    group: 'gameTime',
  },
  {
    key: 'game_variety_sampler_svg',
    bit: 0,
    nameEn: 'Sampler',
    nameRu: 'Sampler',
    descriptionEn: 'Played 2 detectable games.',
    descriptionRu: 'Сыграл в 2 определяемые игры.',
    icon: badgeUrl('game-variety/sampler.svg'),
    group: 'gameVariety',
  },
  {
    key: 'game_variety_dabbler_svg',
    bit: 0,
    nameEn: 'Dabbler',
    nameRu: 'Dabbler',
    descriptionEn: 'Played 5 detectable games.',
    descriptionRu: 'Сыграл в 5 определяемых игр.',
    icon: badgeUrl('game-variety/dabbler.svg'),
    group: 'gameVariety',
  },
  {
    key: 'game_variety_enthusiast_svg',
    bit: 0,
    nameEn: 'Enthusiast',
    nameRu: 'Enthusiast',
    descriptionEn: 'Played 10 detectable games.',
    descriptionRu: 'Сыграл в 10 определяемых игр.',
    icon: badgeUrl('game-variety/enthusiast.svg'),
    group: 'gameVariety',
  },
  {
    key: 'game_variety_ranger_svg',
    bit: 0,
    nameEn: 'Ranger',
    nameRu: 'Ranger',
    descriptionEn: 'Played 15 detectable games.',
    descriptionRu: 'Сыграл в 15 определяемых игр.',
    icon: badgeUrl('game-variety/ranger.svg'),
    group: 'gameVariety',
  },
  {
    key: 'game_variety_explorer_svg',
    bit: 0,
    nameEn: 'Explorer',
    nameRu: 'Explorer',
    descriptionEn: 'Played 20 detectable games.',
    descriptionRu: 'Сыграл в 20 определяемых игр.',
    icon: badgeUrl('game-variety/explorer.svg'),
    group: 'gameVariety',
  },
  {
    key: 'game_variety_adventurer_svg',
    bit: 0,
    nameEn: 'Adventurer',
    nameRu: 'Adventurer',
    descriptionEn: 'Played 30 detectable games.',
    descriptionRu: 'Сыграл в 30 определяемых игр.',
    icon: badgeUrl('game-variety/adventurer.svg'),
    group: 'gameVariety',
  },
  {
    key: 'game_variety_voyager_svg',
    bit: 0,
    nameEn: 'Voyager',
    nameRu: 'Voyager',
    descriptionEn: 'Played 40 detectable games.',
    descriptionRu: 'Сыграл в 40 определяемых игр.',
    icon: badgeUrl('game-variety/voyager.svg'),
    group: 'gameVariety',
  },
  {
    key: 'game_variety_maverick_svg',
    bit: 0,
    nameEn: 'Maverick',
    nameRu: 'Maverick',
    descriptionEn: 'Played 60 detectable games.',
    descriptionRu: 'Сыграл в 60 определяемых игр.',
    icon: badgeUrl('game-variety/maverick.svg'),
    group: 'gameVariety',
  },
  {
    key: 'game_variety_polymath_svg',
    bit: 0,
    nameEn: 'Polymath',
    nameRu: 'Polymath',
    descriptionEn: 'Played 80 detectable games.',
    descriptionRu: 'Сыграл в 80 определяемых игр.',
    icon: badgeUrl('game-variety/polymath.svg'),
    group: 'gameVariety',
  },
  {
    key: 'game_variety_universalist_svg',
    bit: 0,
    nameEn: 'Universalist',
    nameRu: 'Universalist',
    descriptionEn: 'Played 100+ detectable games.',
    descriptionRu: 'Сыграл в 100+ определяемых игр.',
    icon: badgeUrl('game-variety/universalist.svg'),
    group: 'gameVariety',
  },
  {
    key: 'subscriptions_badges_bronze_png',
    bit: 0,
    nameEn: 'Nitro — Bronze (1 Month)',
    nameRu: 'Nitro — Bronze (1 месяц)',
    descriptionEn: 'Nitro tenure: 1 month.',
    descriptionRu: 'Стаж Nitro: 1 месяц.',
    icon: badgeUrl('subscriptions/badges/bronze.png'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_badges_silver_png',
    bit: 0,
    nameEn: 'Nitro — Silver (3 Months)',
    nameRu: 'Nitro — Silver (3 месяца)',
    descriptionEn: 'Nitro tenure: 3 months.',
    descriptionRu: 'Стаж Nitro: 3 месяца.',
    icon: badgeUrl('subscriptions/badges/silver.png'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_badges_gold_png',
    bit: 0,
    nameEn: 'Nitro — Gold (6 Months)',
    nameRu: 'Nitro — Gold (6 месяцев)',
    descriptionEn: 'Nitro tenure: 6 months.',
    descriptionRu: 'Стаж Nitro: 6 месяцев.',
    icon: badgeUrl('subscriptions/badges/gold.png'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_badges_platinum_png',
    bit: 0,
    nameEn: 'Nitro — Platinum (12 Months)',
    nameRu: 'Nitro — Platinum (12 месяцев)',
    descriptionEn: 'Nitro tenure: 12 months.',
    descriptionRu: 'Стаж Nitro: 12 месяцев.',
    icon: badgeUrl('subscriptions/badges/platinum.png'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_badges_diamond_png',
    bit: 0,
    nameEn: 'Nitro — Diamond (24 Months)',
    nameRu: 'Nitro — Diamond (24 месяца)',
    descriptionEn: 'Nitro tenure: 24 months.',
    descriptionRu: 'Стаж Nitro: 24 месяца.',
    icon: badgeUrl('subscriptions/badges/diamond.png'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_badges_emerald_png',
    bit: 0,
    nameEn: 'Nitro — Emerald (36 Months)',
    nameRu: 'Nitro — Emerald (36 месяцев)',
    descriptionEn: 'Nitro tenure: 36 months.',
    descriptionRu: 'Стаж Nitro: 36 месяцев.',
    icon: badgeUrl('subscriptions/badges/emerald.png'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_badges_ruby_png',
    bit: 0,
    nameEn: 'Nitro — Ruby (60 Months)',
    nameRu: 'Nitro — Ruby (60 месяцев)',
    descriptionEn: 'Nitro tenure: 60 months.',
    descriptionRu: 'Стаж Nitro: 60 месяцев.',
    icon: badgeUrl('subscriptions/badges/ruby.png'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_badges_opal_png',
    bit: 0,
    nameEn: 'Nitro — Opal (72+ Months)',
    nameRu: 'Nitro — Opal (72+ месяцев)',
    descriptionEn: 'Nitro tenure: 72+ months.',
    descriptionRu: 'Стаж Nitro: 72+ месяцев.',
    icon: badgeUrl('subscriptions/badges/opal.png'),
    group: 'nitro',
  },
  {
    key: 'boosts_discord_boost_1_svg',
    bit: 0,
    nameEn: 'Server Boosting — 1 Month',
    nameRu: 'Буст сервера — 1 месяц',
    descriptionEn: 'Boosting for 1 month.',
    descriptionRu: 'Буст 1 месяц.',
    icon: badgeUrl('boosts/discord-boost-1.svg'),
    group: 'boost',
  },
  {
    key: 'boosts_discord_boost_2_svg',
    bit: 0,
    nameEn: 'Server Boosting — 2 Months',
    nameRu: 'Буст сервера — 2 месяца',
    descriptionEn: 'Boosting for 2 months.',
    descriptionRu: 'Буст 2 месяца.',
    icon: badgeUrl('boosts/discord-boost-2.svg'),
    group: 'boost',
  },
  {
    key: 'boosts_discord_boost_3_svg',
    bit: 0,
    nameEn: 'Server Boosting — 3 Months',
    nameRu: 'Буст сервера — 3 месяца',
    descriptionEn: 'Boosting for 3 months.',
    descriptionRu: 'Буст 3 месяца.',
    icon: badgeUrl('boosts/discord-boost-3.svg'),
    group: 'boost',
  },
  {
    key: 'boosts_discord_boost_4_svg',
    bit: 0,
    nameEn: 'Server Boosting — 6 Months',
    nameRu: 'Буст сервера — 6 месяцев',
    descriptionEn: 'Boosting for 6 months.',
    descriptionRu: 'Буст 6 месяцев.',
    icon: badgeUrl('boosts/discord-boost-4.svg'),
    group: 'boost',
  },
  {
    key: 'boosts_discord_boost_5_svg',
    bit: 0,
    nameEn: 'Server Boosting — 9 Months',
    nameRu: 'Буст сервера — 9 месяцев',
    descriptionEn: 'Boosting for 9 months.',
    descriptionRu: 'Буст 9 месяцев.',
    icon: badgeUrl('boosts/discord-boost-5.svg'),
    group: 'boost',
  },
  {
    key: 'boosts_discord_boost_6_svg',
    bit: 0,
    nameEn: 'Server Boosting — 1 Year',
    nameRu: 'Буст сервера — 1 год',
    descriptionEn: 'Boosting for 1 year.',
    descriptionRu: 'Буст 1 год.',
    icon: badgeUrl('boosts/discord-boost-6.svg'),
    group: 'boost',
  },
  {
    key: 'boosts_discord_boost_7_svg',
    bit: 0,
    nameEn: 'Server Boosting — 15 Months',
    nameRu: 'Буст сервера — 15 месяцев',
    descriptionEn: 'Boosting for 1 year 3 months.',
    descriptionRu: 'Буст 1 год 3 месяца.',
    icon: badgeUrl('boosts/discord-boost-7.svg'),
    group: 'boost',
  },
  {
    key: 'boosts_discord_boost_8_svg',
    bit: 0,
    nameEn: 'Server Boosting — 18 Months',
    nameRu: 'Буст сервера — 18 месяцев',
    descriptionEn: 'Boosting for 1 year 6 months.',
    descriptionRu: 'Буст 1 год 6 месяцев.',
    icon: badgeUrl('boosts/discord-boost-8.svg'),
    group: 'boost',
  },
  {
    key: 'boosts_discord_boost_9_svg',
    bit: 0,
    nameEn: 'Server Boosting — 2 Years',
    nameRu: 'Буст сервера — 2 года',
    descriptionEn: 'Boosting for 2 years.',
    descriptionRu: 'Буст 2 года.',
    icon: badgeUrl('boosts/discord-boost-9.svg'),
    group: 'boost',
  },
  {
    key: 'server_staff_svg',
    bit: 0,
    nameEn: 'Internal Employee Server',
    nameRu: 'Сервер сотрудников',
    descriptionEn: 'INTERNAL_EMPLOYEE_ONLY servers.',
    descriptionRu: 'Серверы INTERNAL_EMPLOYEE_ONLY.',
    icon: badgeUrl('server/staff.svg'),
    group: 'server',
  },
  {
    key: 'server_partnered_svg',
    bit: 0,
    nameEn: 'Partnered Server',
    nameRu: 'Партнёрский сервер',
    descriptionEn: 'Discord Partner guild badge.',
    descriptionRu: 'Бейдж партнёрского сервера.',
    icon: badgeUrl('server/partnered.svg'),
    group: 'server',
  },
  {
    key: 'server_verified_svg',
    bit: 0,
    nameEn: 'Verified Server',
    nameRu: 'Верифицированный сервер',
    descriptionEn: 'Verified guild badge.',
    descriptionRu: 'Бейдж верифицированного сервера.',
    icon: badgeUrl('server/verified.svg'),
    group: 'server',
  },
  {
    key: 'server_discoverable_boosted_svg',
    bit: 0,
    nameEn: 'Public Server (Boosted)',
    nameRu: 'Публичный сервер (с бустом)',
    descriptionEn: 'Discovery + at least 1 boost.',
    descriptionRu: 'Discovery и минимум 1 буст.',
    icon: badgeUrl('server/discoverable-boosted.svg'),
    group: 'server',
  },
  {
    key: 'server_discoverable_dark_svg',
    bit: 0,
    nameEn: 'Public Server',
    nameRu: 'Публичный сервер',
    descriptionEn: 'Server Discovery badge.',
    descriptionRu: 'Бейдж Server Discovery.',
    icon: badgeUrl('server/discoverable-dark.svg'),
    group: 'server',
  },
  {
    key: 'server_discoverable_light_svg',
    bit: 0,
    nameEn: 'Public Server (Light)',
    nameRu: 'Публичный сервер (светлый)',
    descriptionEn: 'Discovery badge, light theme.',
    descriptionRu: 'Discovery, светлая тема.',
    icon: badgeUrl('server/discoverable-light.svg'),
    group: 'server',
  },
  {
    key: 'server_community_boosted_svg',
    bit: 0,
    nameEn: 'Community Server (Boosted)',
    nameRu: 'Community-сервер (с бустом)',
    descriptionEn: 'Community features + boost.',
    descriptionRu: 'Community + буст.',
    icon: badgeUrl('server/community-boosted.svg'),
    group: 'server',
  },
  {
    key: 'server_community_dark_svg',
    bit: 0,
    nameEn: 'Community Server',
    nameRu: 'Community-сервер',
    descriptionEn: 'Community features enabled.',
    descriptionRu: 'Включены community-функции.',
    icon: badgeUrl('server/community-dark.svg'),
    group: 'server',
  },
  {
    key: 'server_community_light_svg',
    bit: 0,
    nameEn: 'Community Server (Light)',
    nameRu: 'Community-сервер (светлый)',
    descriptionEn: 'Community badge, light theme.',
    descriptionRu: 'Community, светлая тема.',
    icon: badgeUrl('server/community-light.svg'),
    group: 'server',
  },
  {
    key: 'server_boost_0_svg',
    bit: 0,
    nameEn: 'Boosted Server Level 0',
    nameRu: 'Буст сервера — уровень 0',
    descriptionEn: 'Has boosts but no level yet.',
    descriptionRu: 'Есть бусты, но уровня ещё нет.',
    icon: badgeUrl('server/boost-0.svg'),
    group: 'server',
  },
  {
    key: 'server_boost_1_svg',
    bit: 0,
    nameEn: 'Boosted Server Level 1',
    nameRu: 'Буст сервера — уровень 1',
    descriptionEn: 'Boost level 1.',
    descriptionRu: 'Уровень буста 1.',
    icon: badgeUrl('server/boost-1.svg'),
    group: 'server',
  },
  {
    key: 'server_boost_2_dark_svg',
    bit: 0,
    nameEn: 'Boosted Server Level 2',
    nameRu: 'Буст сервера — уровень 2',
    descriptionEn: 'Boost level 2.',
    descriptionRu: 'Уровень буста 2.',
    icon: badgeUrl('server/boost-2-dark.svg'),
    group: 'server',
  },
  {
    key: 'server_boost_2_light_svg',
    bit: 0,
    nameEn: 'Boosted Server Level 2 (Light)',
    nameRu: 'Буст сервера — уровень 2 (светлый)',
    descriptionEn: 'Boost level 2, light theme.',
    descriptionRu: 'Уровень буста 2, светлая тема.',
    icon: badgeUrl('server/boost-2-light.svg'),
    group: 'server',
  },
  {
    key: 'server_boost_3_dark_svg',
    bit: 0,
    nameEn: 'Boosted Server Level 3',
    nameRu: 'Буст сервера — уровень 3',
    descriptionEn: 'Boost level 3.',
    descriptionRu: 'Уровень буста 3.',
    icon: badgeUrl('server/boost-3-dark.svg'),
    group: 'server',
  },
  {
    key: 'server_boost_3_light_svg',
    bit: 0,
    nameEn: 'Boosted Server Level 3 (Light)',
    nameRu: 'Буст сервера — уровень 3 (светлый)',
    descriptionEn: 'Boost level 3, light theme.',
    descriptionRu: 'Уровень буста 3, светлая тема.',
    icon: badgeUrl('server/boost-3-light.svg'),
    group: 'server',
  },
  {
    key: 'server_crown_svg',
    bit: 0,
    nameEn: 'Server Owner',
    nameRu: 'Владелец сервера',
    descriptionEn: 'Guild owner crown.',
    descriptionRu: 'Корона владельца сервера.',
    icon: badgeUrl('server/crown.svg'),
    group: 'server',
  },
  {
    key: 'server_new_here_svg',
    bit: 0,
    nameEn: 'I\'m new here, say hi!',
    nameRu: 'Я новенький — скажите привет!',
    descriptionEn: 'New member on a community server.',
    descriptionRu: 'Новый участник community-сервера.',
    icon: badgeUrl('server/new-here.svg'),
    group: 'server',
  },
  {
    key: 'special_official_svg',
    bit: 0,
    nameEn: 'Official',
    nameRu: 'Official',
    descriptionEn: 'Discord official / AutoMod messages.',
    descriptionRu: 'Официальные / AutoMod сообщения.',
    icon: badgeUrl('special/official.svg'),
    group: 'special',
  },
  {
    key: 'special_system_svg',
    bit: 0,
    nameEn: 'System',
    nameRu: 'System',
    descriptionEn: 'Legacy system message flair.',
    descriptionRu: 'Старый system-флер.',
    icon: badgeUrl('special/system.svg'),
    group: 'special',
  },
  {
    key: 'special_server_svg',
    bit: 0,
    nameEn: 'Server',
    nameRu: 'Server',
    descriptionEn: 'Channel-follow webhook flair.',
    descriptionRu: 'Флер webhook при follow канала.',
    icon: badgeUrl('special/server.svg'),
    group: 'special',
  },
  {
    key: 'special_verified_bot_svg',
    bit: 0,
    nameEn: 'Verified Bot',
    nameRu: 'Verified Bot',
    descriptionEn: 'Verified app flair.',
    descriptionRu: 'Флер верифицированного приложения.',
    icon: badgeUrl('special/verified-bot.svg'),
    group: 'special',
  },
  {
    key: 'special_verified_app_svg',
    bit: 0,
    nameEn: 'Verified App',
    nameRu: 'Verified App',
    descriptionEn: 'Verified app flair (APP label).',
    descriptionRu: 'Флер верифицированного приложения (APP).',
    icon: badgeUrl('special/verified-app.svg'),
    group: 'special',
  },
  {
    key: 'special_bot_svg',
    bit: 0,
    nameEn: 'Bot',
    nameRu: 'Bot',
    descriptionEn: 'Unverified bot flair.',
    descriptionRu: 'Флер неверифицированного бота.',
    icon: badgeUrl('special/bot.svg'),
    group: 'special',
  },
  {
    key: 'special_app_svg',
    bit: 0,
    nameEn: 'App',
    nameRu: 'App',
    descriptionEn: 'Unverified app flair.',
    descriptionRu: 'Флер неверифицированного приложения.',
    icon: badgeUrl('special/app.svg'),
    group: 'special',
  },
  {
    key: 'special_beta_svg',
    bit: 0,
    nameEn: 'Beta',
    nameRu: 'Beta',
    descriptionEn: 'In-beta feature flair.',
    descriptionRu: 'Флер бета-функций.',
    icon: badgeUrl('special/beta.svg'),
    group: 'special',
  },
  {
    key: 'special_light_ai_svg',
    bit: 0,
    nameEn: 'AI (Light)',
    nameRu: 'AI (светлый)',
    descriptionEn: 'Clyde AI flair, light.',
    descriptionRu: 'Флер Clyde AI, светлый.',
    icon: badgeUrl('special/light-ai.svg'),
    group: 'special',
  },
  {
    key: 'special_dark_ai_svg',
    bit: 0,
    nameEn: 'AI (Dark)',
    nameRu: 'AI (тёмный)',
    descriptionEn: 'Clyde AI flair, dark.',
    descriptionRu: 'Флер Clyde AI, тёмный.',
    icon: badgeUrl('special/dark-ai.svg'),
    group: 'special',
  },
  {
    key: 'special_original_poster_svg',
    bit: 0,
    nameEn: 'Original Poster',
    nameRu: 'Original Poster',
    descriptionEn: 'Forum OP flair.',
    descriptionRu: 'Флер автора поста форума.',
    icon: badgeUrl('special/original-poster.svg'),
    group: 'special',
  },
  {
    key: 'fame_spongetext_staff_png',
    bit: 0,
    nameEn: 'Spongetext Staff',
    nameRu: 'Spongetext Staff',
    descriptionEn: 'Hall of Fame: staff badge on Spongetext.',
    descriptionRu: 'Hall of Fame: staff-бейдж у Spongetext.',
    icon: badgeUrl('fame/spongetext-staff.png'),
    group: 'fame',
  },
  {
    key: 'fame_sapphire_mod_png',
    bit: 0,
    nameEn: 'Sapphire Moderator Alumni',
    nameRu: 'Sapphire Moderator Alumni',
    descriptionEn: 'Hall of Fame: Sapphire mod alumni.',
    descriptionRu: 'Hall of Fame: Sapphire mod alumni.',
    icon: badgeUrl('fame/sapphire-mod.png'),
    group: 'fame',
  },
  {
    key: 'fame_gear_mod_png',
    bit: 0,
    nameEn: 'GearBot Moderator Alumni',
    nameRu: 'GearBot Moderator Alumni',
    descriptionEn: 'Hall of Fame: GearBot mod alumni.',
    descriptionRu: 'Hall of Fame: GearBot mod alumni.',
    icon: badgeUrl('fame/gear-mod.png'),
    group: 'fame',
  },
  {
    key: 'fame_wumpus_png',
    bit: 0,
    nameEn: 'Wumpus Chatbot',
    nameRu: 'Wumpus Chatbot',
    descriptionEn: 'Hall of Fame: early Discord chatbot.',
    descriptionRu: 'Hall of Fame: ранний чатбот Discord.',
    icon: badgeUrl('fame/wumpus.png'),
    group: 'fame',
  },
  {
    key: 'koth_hype_squad_balance_svg',
    bit: 0,
    nameEn: 'King of the Hat Balance',
    nameRu: 'King of the Hat Balance',
    descriptionEn: '2019 King of the Hat HypeSquad Balance.',
    descriptionRu: 'HypeSquad Balance — King of the Hat 2019.',
    icon: badgeUrl('koth-hype-squad-balance.svg'),
    group: 'fame',
  },
  {
    key: 'golden_hype_squad_balance_svg',
    bit: 0,
    nameEn: 'Golden HypeSquad Balance',
    nameRu: 'Golden HypeSquad Balance',
    descriptionEn: 'Snowsgiving 2019 gold Balance badge.',
    descriptionRu: 'Золотой Balance на Snowsgiving 2019.',
    icon: badgeUrl('golden-hype-squad-balance.svg'),
    group: 'fame',
  },
  {
    key: 'old_discord_mod_svg',
    bit: 0,
    nameEn: 'Certified Moderator (Legacy)',
    nameRu: 'Certified Moderator (legacy)',
    descriptionEn: 'Pre-2022 moderator badge art.',
    descriptionRu: 'Старый арт бейджа модератора.',
    icon: badgeUrl('old-discord-mod.svg'),
    group: 'legacy',
  },
  {
    key: 'old_discord_partner_png',
    bit: 0,
    nameEn: 'Partner (Legacy Art)',
    nameRu: 'Partner (старый арт)',
    descriptionEn: 'Pre-2022 partner badge art.',
    descriptionRu: 'Старый арт бейджа Partner.',
    icon: badgeUrl('old-discord-partner.png'),
    group: 'legacy',
  },
  {
    key: 'subscriptions_legacy_bronze_svg',
    bit: 0,
    nameEn: 'Nitro Legacy — Bronze',
    nameRu: 'Nitro Legacy — Bronze',
    descriptionEn: 'Legacy Nitro tenure art.',
    descriptionRu: 'Старый арт стажа Nitro.',
    icon: badgeUrl('subscriptions/legacy/bronze.svg'),
    group: 'nitroLegacy',
  },
  {
    key: 'subscriptions_legacy_silver_svg',
    bit: 0,
    nameEn: 'Nitro Legacy — Silver',
    nameRu: 'Nitro Legacy — Silver',
    descriptionEn: 'Legacy Nitro tenure art.',
    descriptionRu: 'Старый арт стажа Nitro.',
    icon: badgeUrl('subscriptions/legacy/silver.svg'),
    group: 'nitroLegacy',
  },
  {
    key: 'subscriptions_legacy_gold_svg',
    bit: 0,
    nameEn: 'Nitro Legacy — Gold',
    nameRu: 'Nitro Legacy — Gold',
    descriptionEn: 'Legacy Nitro tenure art.',
    descriptionRu: 'Старый арт стажа Nitro.',
    icon: badgeUrl('subscriptions/legacy/gold.svg'),
    group: 'nitroLegacy',
  },
  {
    key: 'subscriptions_legacy_platinum_svg',
    bit: 0,
    nameEn: 'Nitro Legacy — Platinum',
    nameRu: 'Nitro Legacy — Platinum',
    descriptionEn: 'Legacy Nitro tenure art.',
    descriptionRu: 'Старый арт стажа Nitro.',
    icon: badgeUrl('subscriptions/legacy/platinum.svg'),
    group: 'nitroLegacy',
  },
  {
    key: 'subscriptions_legacy_diamond_svg',
    bit: 0,
    nameEn: 'Nitro Legacy — Diamond',
    nameRu: 'Nitro Legacy — Diamond',
    descriptionEn: 'Legacy Nitro tenure art.',
    descriptionRu: 'Старый арт стажа Nitro.',
    icon: badgeUrl('subscriptions/legacy/diamond.svg'),
    group: 'nitroLegacy',
  },
  {
    key: 'subscriptions_legacy_emerald_svg',
    bit: 0,
    nameEn: 'Nitro Legacy — Emerald',
    nameRu: 'Nitro Legacy — Emerald',
    descriptionEn: 'Legacy Nitro tenure art.',
    descriptionRu: 'Старый арт стажа Nitro.',
    icon: badgeUrl('subscriptions/legacy/emerald.svg'),
    group: 'nitroLegacy',
  },
  {
    key: 'subscriptions_legacy_ruby_svg',
    bit: 0,
    nameEn: 'Nitro Legacy — Ruby',
    nameRu: 'Nitro Legacy — Ruby',
    descriptionEn: 'Legacy Nitro tenure art.',
    descriptionRu: 'Старый арт стажа Nitro.',
    icon: badgeUrl('subscriptions/legacy/ruby.svg'),
    group: 'nitroLegacy',
  },
  {
    key: 'subscriptions_legacy_fire_svg',
    bit: 0,
    nameEn: 'Nitro Legacy — Fire',
    nameRu: 'Nitro Legacy — Fire',
    descriptionEn: 'Legacy Nitro tenure art.',
    descriptionRu: 'Старый арт стажа Nitro.',
    icon: badgeUrl('subscriptions/legacy/fire.svg'),
    group: 'nitroLegacy',
  },
  {
    key: 'subscriptions_bronze_svg',
    bit: 0,
    nameEn: 'Nitro — Bronze (SVG)',
    nameRu: 'Nitro — Bronze (SVG)',
    descriptionEn: 'Nitro tenure hover SVG.',
    descriptionRu: 'SVG стажа Nitro.',
    icon: badgeUrl('subscriptions/bronze.svg'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_silver_svg',
    bit: 0,
    nameEn: 'Nitro — Silver (SVG)',
    nameRu: 'Nitro — Silver (SVG)',
    descriptionEn: 'Nitro tenure hover SVG.',
    descriptionRu: 'SVG стажа Nitro.',
    icon: badgeUrl('subscriptions/silver.svg'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_gold_svg',
    bit: 0,
    nameEn: 'Nitro — Gold (SVG)',
    nameRu: 'Nitro — Gold (SVG)',
    descriptionEn: 'Nitro tenure hover SVG.',
    descriptionRu: 'SVG стажа Nitro.',
    icon: badgeUrl('subscriptions/gold.svg'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_platinum_svg',
    bit: 0,
    nameEn: 'Nitro — Platinum (SVG)',
    nameRu: 'Nitro — Platinum (SVG)',
    descriptionEn: 'Nitro tenure hover SVG.',
    descriptionRu: 'SVG стажа Nitro.',
    icon: badgeUrl('subscriptions/platinum.svg'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_diamond_svg',
    bit: 0,
    nameEn: 'Nitro — Diamond (SVG)',
    nameRu: 'Nitro — Diamond (SVG)',
    descriptionEn: 'Nitro tenure hover SVG.',
    descriptionRu: 'SVG стажа Nitro.',
    icon: badgeUrl('subscriptions/diamond.svg'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_emerald_svg',
    bit: 0,
    nameEn: 'Nitro — Emerald (SVG)',
    nameRu: 'Nitro — Emerald (SVG)',
    descriptionEn: 'Nitro tenure hover SVG.',
    descriptionRu: 'SVG стажа Nitro.',
    icon: badgeUrl('subscriptions/emerald.svg'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_ruby_svg',
    bit: 0,
    nameEn: 'Nitro — Ruby (SVG)',
    nameRu: 'Nitro — Ruby (SVG)',
    descriptionEn: 'Nitro tenure hover SVG.',
    descriptionRu: 'SVG стажа Nitro.',
    icon: badgeUrl('subscriptions/ruby.svg'),
    group: 'nitro',
  },
  {
    key: 'subscriptions_opal_svg',
    bit: 0,
    nameEn: 'Nitro — Opal (SVG)',
    nameRu: 'Nitro — Opal (SVG)',
    descriptionEn: 'Nitro tenure hover SVG.',
    descriptionRu: 'SVG стажа Nitro.',
    icon: badgeUrl('subscriptions/opal.svg'),
    group: 'nitro',
  },
  {
    key: 'guilds_1_svg',
    bit: 0,
    nameEn: 'Server Tag #1',
    nameRu: 'Server Tag #1',
    descriptionEn: 'Legacy tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Legacy-тег).',
    icon: badgeUrl('guilds/1.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_2_svg',
    bit: 0,
    nameEn: 'Server Tag #2',
    nameRu: 'Server Tag #2',
    descriptionEn: 'Legacy tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Legacy-тег).',
    icon: badgeUrl('guilds/2.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_3_svg',
    bit: 0,
    nameEn: 'Server Tag #3',
    nameRu: 'Server Tag #3',
    descriptionEn: 'Legacy tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Legacy-тег).',
    icon: badgeUrl('guilds/3.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_4_svg',
    bit: 0,
    nameEn: 'Server Tag #4',
    nameRu: 'Server Tag #4',
    descriptionEn: 'Legacy tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Legacy-тег).',
    icon: badgeUrl('guilds/4.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_5_svg',
    bit: 0,
    nameEn: 'Server Tag #5',
    nameRu: 'Server Tag #5',
    descriptionEn: 'Legacy tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Legacy-тег).',
    icon: badgeUrl('guilds/5.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_6_svg',
    bit: 0,
    nameEn: 'Server Tag #6',
    nameRu: 'Server Tag #6',
    descriptionEn: 'Legacy tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Legacy-тег).',
    icon: badgeUrl('guilds/6.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_7_svg',
    bit: 0,
    nameEn: 'Server Tag #7',
    nameRu: 'Server Tag #7',
    descriptionEn: 'Legacy tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Legacy-тег).',
    icon: badgeUrl('guilds/7.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_8_svg',
    bit: 0,
    nameEn: 'Server Tag #8',
    nameRu: 'Server Tag #8',
    descriptionEn: 'Legacy tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Legacy-тег).',
    icon: badgeUrl('guilds/8.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_9_svg',
    bit: 0,
    nameEn: 'Server Tag #9',
    nameRu: 'Server Tag #9',
    descriptionEn: 'Legacy tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Legacy-тег).',
    icon: badgeUrl('guilds/9.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_10_svg',
    bit: 0,
    nameEn: 'Server Tag #10',
    nameRu: 'Server Tag #10',
    descriptionEn: 'Legacy tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Legacy-тег).',
    icon: badgeUrl('guilds/10.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_11_svg',
    bit: 0,
    nameEn: 'Server Tag #11',
    nameRu: 'Server Tag #11',
    descriptionEn: 'Legacy tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Legacy-тег).',
    icon: badgeUrl('guilds/11.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_12_svg',
    bit: 0,
    nameEn: 'Server Tag #12',
    nameRu: 'Server Tag #12',
    descriptionEn: 'Free tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Бесплатный тег).',
    icon: badgeUrl('guilds/12.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_13_svg',
    bit: 0,
    nameEn: 'Server Tag #13',
    nameRu: 'Server Tag #13',
    descriptionEn: 'Free tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Бесплатный тег).',
    icon: badgeUrl('guilds/13.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_14_svg',
    bit: 0,
    nameEn: 'Server Tag #14',
    nameRu: 'Server Tag #14',
    descriptionEn: 'Free tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Бесплатный тег).',
    icon: badgeUrl('guilds/14.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_15_svg',
    bit: 0,
    nameEn: 'Server Tag #15',
    nameRu: 'Server Tag #15',
    descriptionEn: 'Free tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Бесплатный тег).',
    icon: badgeUrl('guilds/15.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_16_svg',
    bit: 0,
    nameEn: 'Server Tag #16',
    nameRu: 'Server Tag #16',
    descriptionEn: 'Free tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Бесплатный тег).',
    icon: badgeUrl('guilds/16.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_17_svg',
    bit: 0,
    nameEn: 'Server Tag #17',
    nameRu: 'Server Tag #17',
    descriptionEn: 'Free tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Бесплатный тег).',
    icon: badgeUrl('guilds/17.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_18_svg',
    bit: 0,
    nameEn: 'Server Tag #18',
    nameRu: 'Server Tag #18',
    descriptionEn: 'Free tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Бесплатный тег).',
    icon: badgeUrl('guilds/18.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_19_svg',
    bit: 0,
    nameEn: 'Server Tag #19',
    nameRu: 'Server Tag #19',
    descriptionEn: 'Free tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Бесплатный тег).',
    icon: badgeUrl('guilds/19.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_20_svg',
    bit: 0,
    nameEn: 'Server Tag #20',
    nameRu: 'Server Tag #20',
    descriptionEn: 'Free tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Бесплатный тег).',
    icon: badgeUrl('guilds/20.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_21_svg',
    bit: 0,
    nameEn: 'Server Tag #21',
    nameRu: 'Server Tag #21',
    descriptionEn: 'Free tag guild tag icon.',
    descriptionRu: 'Иконка guild tag (Бесплатный тег).',
    icon: badgeUrl('guilds/21.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_22_svg',
    bit: 0,
    nameEn: 'Server Tag #22',
    nameRu: 'Server Tag #22',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/22.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_23_svg',
    bit: 0,
    nameEn: 'Server Tag #23',
    nameRu: 'Server Tag #23',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/23.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_24_svg',
    bit: 0,
    nameEn: 'Server Tag #24',
    nameRu: 'Server Tag #24',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/24.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_25_svg',
    bit: 0,
    nameEn: 'Server Tag #25',
    nameRu: 'Server Tag #25',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/25.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_26_svg',
    bit: 0,
    nameEn: 'Server Tag #26',
    nameRu: 'Server Tag #26',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/26.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_27_svg',
    bit: 0,
    nameEn: 'Server Tag #27',
    nameRu: 'Server Tag #27',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/27.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_28_svg',
    bit: 0,
    nameEn: 'Server Tag #28',
    nameRu: 'Server Tag #28',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/28.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_29_svg',
    bit: 0,
    nameEn: 'Server Tag #29',
    nameRu: 'Server Tag #29',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/29.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_30_svg',
    bit: 0,
    nameEn: 'Server Tag #30',
    nameRu: 'Server Tag #30',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/30.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_31_svg',
    bit: 0,
    nameEn: 'Server Tag #31',
    nameRu: 'Server Tag #31',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/31.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_32_svg',
    bit: 0,
    nameEn: 'Server Tag #32',
    nameRu: 'Server Tag #32',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/32.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_33_svg',
    bit: 0,
    nameEn: 'Server Tag #33',
    nameRu: 'Server Tag #33',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/33.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_34_svg',
    bit: 0,
    nameEn: 'Server Tag #34',
    nameRu: 'Server Tag #34',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/34.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_35_svg',
    bit: 0,
    nameEn: 'Server Tag #35',
    nameRu: 'Server Tag #35',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/35.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_36_svg',
    bit: 0,
    nameEn: 'Server Tag #36',
    nameRu: 'Server Tag #36',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/36.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_37_svg',
    bit: 0,
    nameEn: 'Server Tag #37',
    nameRu: 'Server Tag #37',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/37.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_38_svg',
    bit: 0,
    nameEn: 'Server Tag #38',
    nameRu: 'Server Tag #38',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/38.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_39_svg',
    bit: 0,
    nameEn: 'Server Tag #39',
    nameRu: 'Server Tag #39',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/39.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_40_svg',
    bit: 0,
    nameEn: 'Server Tag #40',
    nameRu: 'Server Tag #40',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/40.svg'),
    group: 'tags',
  },
  {
    key: 'guilds_41_svg',
    bit: 0,
    nameEn: 'Server Tag #41',
    nameRu: 'Server Tag #41',
    descriptionEn: 'Badge pack guild tag icon.',
    descriptionRu: 'Иконка guild tag (Badge pack).',
    icon: badgeUrl('guilds/41.svg'),
    group: 'tags',
  },
]

export function badgesFromFlags(flags: number | null | undefined): BadgeDef[] {
  const value = flags ?? 0
  return BADGE_CATALOG.filter((b) => b.bit !== 0 && (value & b.bit) === b.bit)
}

