/** SVG assets under /lookup/badges/ (Vite base). Catalog badges + Nitro/boost variants. */
export type BadgeDef = {
  key: string
  /** public_flags bit; 0 = catalog-only (Nitro / boost tenure, not in public_flags) */
  bit: number
  nameEn: string
  nameRu: string
  descriptionEn?: string
  descriptionRu?: string
  icon: string
  group: 'flags' | 'nitro' | 'boost'
}

const badgeUrl = (file: string) => `${import.meta.env.BASE_URL}badges/${file}`

/** Public UserFlags + commonly catalogued Nitro/boost badges (2026). */
export const BADGE_CATALOG: BadgeDef[] = [
  {
    key: 'staff',
    bit: 1 << 0,
    nameEn: 'Discord Employee',
    nameRu: 'Сотрудник Discord',
    descriptionEn: 'Official Discord staff.',
    descriptionRu: 'Официальный сотрудник Discord.',
    icon: badgeUrl('staff.svg'),
    group: 'flags',
  },
  {
    key: 'partner',
    bit: 1 << 1,
    nameEn: 'Partnered Server Owner',
    nameRu: 'Владелец партнёрского сервера',
    descriptionEn: 'Owns a Discord Partner server.',
    descriptionRu: 'Владелец сервера Discord Partner.',
    icon: badgeUrl('partnered_server_owner.svg'),
    group: 'flags',
  },
  {
    key: 'hypesquad',
    bit: 1 << 2,
    nameEn: 'HypeSquad Events',
    nameRu: 'HypeSquad Events',
    descriptionEn: 'HypeSquad Events member.',
    descriptionRu: 'Участник HypeSquad Events.',
    icon: badgeUrl('hypesquad_events.svg'),
    group: 'flags',
  },
  {
    key: 'bug1',
    bit: 1 << 3,
    nameEn: 'Bug Hunter Level 1',
    nameRu: 'Bug Hunter Level 1',
    descriptionEn: 'Reported bugs to Discord.',
    descriptionRu: 'Сообщал о багах Discord.',
    icon: badgeUrl('bug_hunter_level_1.svg'),
    group: 'flags',
  },
  {
    key: 'hype_bravery',
    bit: 1 << 6,
    nameEn: 'HypeSquad Bravery',
    nameRu: 'HypeSquad Bravery',
    descriptionEn: 'House Bravery member.',
    descriptionRu: 'Дом Bravery.',
    icon: badgeUrl('hypesquad_bravery.svg'),
    group: 'flags',
  },
  {
    key: 'hype_brilliance',
    bit: 1 << 7,
    nameEn: 'HypeSquad Brilliance',
    nameRu: 'HypeSquad Brilliance',
    descriptionEn: 'House Brilliance member.',
    descriptionRu: 'Дом Brilliance.',
    icon: badgeUrl('hypesquad_brilliance.svg'),
    group: 'flags',
  },
  {
    key: 'hype_balance',
    bit: 1 << 8,
    nameEn: 'HypeSquad Balance',
    nameRu: 'HypeSquad Balance',
    descriptionEn: 'House Balance member.',
    descriptionRu: 'Дом Balance.',
    icon: badgeUrl('hypesquad_balance.svg'),
    group: 'flags',
  },
  {
    key: 'premium_early',
    bit: 1 << 9,
    nameEn: 'Early Supporter',
    nameRu: 'Early Supporter',
    descriptionEn: 'Early Nitro purchaser.',
    descriptionRu: 'Ранний покупатель Nitro.',
    icon: badgeUrl('early_supporter.svg'),
    group: 'flags',
  },
  {
    key: 'team',
    bit: 1 << 10,
    nameEn: 'Team User',
    nameRu: 'Team User',
    descriptionEn: 'Discord Team pseudo-user.',
    descriptionRu: 'Псевдопользователь Discord Team.',
    icon: badgeUrl('team_user.svg'),
    group: 'flags',
  },
  {
    key: 'bug2',
    bit: 1 << 14,
    nameEn: 'Bug Hunter Level 2',
    nameRu: 'Bug Hunter Level 2',
    descriptionEn: 'Higher-tier bug hunter.',
    descriptionRu: 'Bug Hunter высшего уровня.',
    icon: badgeUrl('bug_hunter_level_2.svg'),
    group: 'flags',
  },
  {
    key: 'verified_bot',
    bit: 1 << 16,
    nameEn: 'Verified Bot',
    nameRu: 'Verified Bot',
    descriptionEn: 'Bot verified by Discord.',
    descriptionRu: 'Бот, верифицированный Discord.',
    icon: badgeUrl('verified_bot.svg'),
    group: 'flags',
  },
  {
    key: 'verified_dev',
    bit: 1 << 17,
    nameEn: 'Early Verified Bot Developer',
    nameRu: 'Early Verified Bot Developer',
    descriptionEn: 'Early verified bot developer.',
    descriptionRu: 'Ранний верифицированный разработчик ботов.',
    icon: badgeUrl('early_verified_developer.svg'),
    group: 'flags',
  },
  {
    key: 'mod_alumni',
    bit: 1 << 18,
    nameEn: 'Moderator Programs Alumni',
    nameRu: 'Moderator Programs Alumni',
    descriptionEn: 'Discord moderator programs alumni.',
    descriptionRu: 'Выпускник программ модерации Discord.',
    icon: badgeUrl('certified_moderator.svg'),
    group: 'flags',
  },
  {
    key: 'active_dev',
    bit: 1 << 22,
    nameEn: 'Active Developer',
    nameRu: 'Active Developer',
    descriptionEn: 'Owns an active Discord application.',
    descriptionRu: 'Владелец активного приложения Discord.',
    icon: badgeUrl('active_developer.svg'),
    group: 'flags',
  },
  {
    key: 'quest',
    bit: 0,
    nameEn: 'Quest Completed',
    nameRu: 'Quest Completed',
    descriptionEn: 'Completed a Discord Quest (profile badge; not a public_flags bit).',
    descriptionRu: 'Завершил Discord Quest (бейдж профиля; не бит public_flags).',
    icon: badgeUrl('quest_completed.svg'),
    group: 'flags',
  },
  {
    key: 'nitro',
    bit: 0,
    nameEn: 'Nitro',
    nameRu: 'Nitro',
    descriptionEn: 'Active Nitro subscription (premium_type; not public_flags).',
    descriptionRu: 'Активная подписка Nitro (premium_type; не public_flags).',
    icon: badgeUrl('nitro.svg'),
    group: 'nitro',
  },
  {
    key: 'boost_1',
    bit: 0,
    nameEn: 'Server Boosting — 1 Month',
    nameRu: 'Буст сервера — 1 месяц',
    icon: badgeUrl('boosting_1_months.svg'),
    group: 'boost',
  },
  {
    key: 'boost_2',
    bit: 0,
    nameEn: 'Server Boosting — 2 Months',
    nameRu: 'Буст сервера — 2 месяца',
    icon: badgeUrl('boosting_2_months.svg'),
    group: 'boost',
  },
  {
    key: 'boost_3',
    bit: 0,
    nameEn: 'Server Boosting — 3 Months',
    nameRu: 'Буст сервера — 3 месяца',
    icon: badgeUrl('boosting_3_months.svg'),
    group: 'boost',
  },
  {
    key: 'boost_6',
    bit: 0,
    nameEn: 'Server Boosting — 6 Months',
    nameRu: 'Буст сервера — 6 месяцев',
    icon: badgeUrl('boosting_6_months.svg'),
    group: 'boost',
  },
  {
    key: 'boost_9',
    bit: 0,
    nameEn: 'Server Boosting — 9 Months',
    nameRu: 'Буст сервера — 9 месяцев',
    icon: badgeUrl('boosting_9_months.svg'),
    group: 'boost',
  },
  {
    key: 'boost_12',
    bit: 0,
    nameEn: 'Server Boosting — 12 Months',
    nameRu: 'Буст сервера — 12 месяцев',
    icon: badgeUrl('boosting_12_months.svg'),
    group: 'boost',
  },
  {
    key: 'boost_15',
    bit: 0,
    nameEn: 'Server Boosting — 15 Months',
    nameRu: 'Буст сервера — 15 месяцев',
    icon: badgeUrl('boosting_15_months.svg'),
    group: 'boost',
  },
  {
    key: 'boost_18',
    bit: 0,
    nameEn: 'Server Boosting — 18 Months',
    nameRu: 'Буст сервера — 18 месяцев',
    icon: badgeUrl('boosting_18_months.svg'),
    group: 'boost',
  },
  {
    key: 'boost_24',
    bit: 0,
    nameEn: 'Server Boosting — 24 Months',
    nameRu: 'Буст сервера — 24 месяца',
    icon: badgeUrl('boosting_24_months.svg'),
    group: 'boost',
  },
]

export function badgesFromFlags(flags: number | null | undefined): BadgeDef[] {
  const value = flags ?? 0
  return BADGE_CATALOG.filter((b) => b.bit !== 0 && (value & b.bit) === b.bit)
}
